# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatKeepcoding' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for ChatKeepcoding
  pod 'MessageKit', '~> 0.13.1'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database'
  pod 'FirebaseStorage'
  pod 'Kingfisher', '~> 4.0'

end
